// ADMIN LOG_IN
export const LOG_IN_REQUEST = "LOG_IN_REQUEST" 
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS" 
export const LOG_IN_FAIL = "LOG_IN_FAIL" 

// GET DATA 

export const GET_CLIENT_REQUEST = "GET_CLIENT_REQUEST" 
export const GET_CLIENT_SUCCESS = "GET_CLIENT_SUCCESS" 
export const GET_CLIENT_FAIL = "GET_CLIENT_FAIL"

export const UPDATE_CLIENT_REQUEST = "GET_SINGLR_CLIENT_REQUEST"
export const UPDATE_CLIENT_SUCCESS = "GET_SINGLR_CLIENT_SUCCESS"
export const UPDATE_CLIENT_FAIL = "GET_SINGLR_CLIENT_FAIL"

export const ADD_CLIENT_REQUEST = "ADD_CLIENT_REQUEST"
export const ADD_CLIENT_SUCCESS = "ADD_CLIENT_SUCCESS"
export const ADD_CLIENT_FAIL = "ADD_CLIENT_FAIL"


// transfer money

export const TRANSFER_MONEY_REQUEST = "TRANSFER_MONEY_REQUEST"
export const TRANSFER_MONEY_SUCCESS = "TRANSFER_MONEY_REQUEST"
export const TRANSFER_MONEY_FAIL = "TRANSFER_MONEY_SUCCESS"
// profile deatils
export const GET_PRODILE_REQUEST = "GET_PROFILE_REQUEST"
export const GET_PRODILE_SUCCESS = "GET_PROFILE_SUCCESS"
export const GET_PRODILE_FAIL = "GET_PROFILE_FAIL"
